version: 2
builds:
  - binary: grok_exporter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64

archives:
  - id: default
    format: binary
  - id: targz
    format: tar.gz
